### ISSUE TITLE
new session error

### ISSUE THREAD

**Issue by krll-k** [talmobi/tor-request#1]
`kzntsv: ~/tor-request $ mocha test/test.js 
 
 
  Testing request and tor-request against http://api.ipify.org
    test http request
The requests public ip was: 52.49.96.251
       should return without error (181ms)                                                                                                                                                                  
    test https (SSL) request. Should match last returned ip.
The requests public ip was: 52.49.96.251
       should return without error (324ms)                                                                                                                                                                  
    test http tor-request
The requests public ip was: 193.171.202.150
       should return without error (497ms)                                                                                                                                                                  
    request a new tor session with tr.newTorSession
      1) should return without error                                                                                                                                                                        
    verify that we have a new tor session (new ip)
      2) should return without error                                                                                                                                                                        
    test http bindings between tor-request and request
      test http GET tor-request
method was: GET
         should return without error (593ms)                                                                                                                                                                
      test http POST tor-request
method was: POST
         should return without error (442ms)                                                                                                                                                                
      test http HEAD tor-request
method was: HEAD
         should return without error (459ms)                                                                                                                                                                
      test http DELETE tor-request
method was: DELETE
         should return without error (607ms)                                                                                                                                                                
      test http PUT tor-request
method was: PUT
the requests public ip was: 
         should return without error (481ms)                                                                                                                                                                
 
 
  8 passing (4s)
  2 failing
 
  1) Testing request and tor-request against http://api.ipify.org request a new tor session with tr.newTorSession should return without error:
     Uncaught Error: connect ECONNREFUSED
      at errnoException (net.js:904:11)
      at Object.afterConnect [as oncomplete] (net.js:895:19)
 
  2) Testing request and tor-request against http://api.ipify.org verify that we have a new tor session (new ip) should return without error:
     Uncaught Error: ip has not changed after new tor session was requested.
      at Object.callback (test/test.js:58:60)
      at Request._callback (index.js:61:12)
      at Request.self.callback (node_modules/request/request.js:199:22)
      at Request.<anonymous> (node_modules/request/request.js:1036:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:963:12)
      at _stream_readable.js:920:16`

**Comment by talmobi** [comment]
Hello!

It seems it's failing to connect to your tor clients control port to signal for a new session - do you have the ControlPort enabled (uncommented) in your /etc/tor/torrc file?

Here's a small guide to set it up:
https://github.com/talmobi/tor-request#optional-configuring-tor-enabling-the-controlport

**Comment by krll-k** [comment]
thx.
