### ISSUE TITLE
Connection timeouts

### ISSUE THREAD

**Issue by ktkaushik** [talmobi/tor-request#10]
hey @talmobi 

I keep getting `Error: Connection Timed Out` on the example you have given in the documentation.

Is there some setting that i am perhaps missing out?

**Comment by talmobi** [comment]
Hello!

Sorry, I had destroyed the VPS where the Demo was running -- I've re-hosted it and it should work now!

https://tor.jin.fi

Also, in case that wasn't your question, sometimes tor (and therefore the socks library and tor-request) will get 404 timeouts because a tor node has probably restarted or moved and the keys haven't been updated -- it should automatically resolve itself (usually within 10-60 seconds).

**Comment by ktkaushik** [comment]
Hey

You are correct that it was not really my question but thanks for hosting the demo, that helps. I've now cloned your repo and playing around the demo and it seems to be fine.

I am going to try to automate requesting a new ip after a set period of time.

My main question was: 

```javascript
var tr = require('tor-request');
tr.request('https://api.ipify.org', function (err, res, body) {
  if (!err && res.statusCode == 200) {
    console.log("Your public (through Tor) IP is: " + body);
  }
});
```

This is where i have been getting connection timeouts

**Comment by ktkaushik** [comment]
also, i can see the __socks__ client throws this error

**Comment by talmobi** [comment]
What error?

Make sure you install and run `tor` before using `tor-request`, see the requirements: https://github.com/talmobi/tor-request#requirements

If you're using a unix system it's probably as simple as running `apt-get install tor` or `brew install tor && tor &`

If you want to use the tor ControlPort (to dynamically request new IP without restarting the tor client) -- you additionally need to cofigure your torrc file to enable the Tor ControlPort -- see the requirements section of the README: https://github.com/talmobi/tor-request#requirements

**Comment by talmobi** [comment]
Oh, yes, sock client throws the error -- yes, that's probably since tor itself is trying to use an outdated tor node -- it should correct itself in 10-60seconds usually.

**Comment by ktkaushik** [comment]
Cool, i will check it out and get back to you on monday.

Thanks.

**Comment by talmobi** [comment]
Did you get it working?

**Comment by ktkaushik** [comment]
@talmobi yes i did. Sorry, i will update this.
