### ISSUE TITLE
HTTP 503  status

### ISSUE THREAD

**Issue by dcromster** [talmobi/tor-request#13]
Hello!
When I try make request to http://emls.ru/flats/?query=s/1/r2/1/is_auction/2/type/2/place/address/reg/2/dept/2/dist/9/sort1/1/dir1/2/sort2/3/dir2/1//interval/5 I got 503, but from browser 200.

I think problem with User-Agent. How I can set UA like browser?

**Comment by talmobi** [comment]
Refer to the https://github.com/request/request#custom-http-headers to specify your own headers ( like User-Agent ).

basically: ` tr.request({ url: 'google.com', headers: { 'user-agent': 'giraffe' }}, function ( err, response, body ) { /*...*/ })`

That url works for me fine for tor-request and request ( status 200 )

```js
var tr = require( './index.js' )
var request = require( 'request' )

var url = 'http://emls.ru/flats/?query=s/1/r2/1/is_auction/2/type/2/place/address/reg/2/dept/2/dist/9/sort1/1/dir1/2/sort2/3/dir2/1//interval/5'

console.log( 'making request: ' )
request( url, function ( err, response, body ) {
  if ( err ) throw err
  body0 = body

  console.log( 'statusCode: ' + response.statusCode )
  tr.request( url, function ( err, response, body ) {
    if ( err ) throw err

    console.log( 'statusCode: ' + response.statusCode )
  })
})
```

It's possible that some servers identify tor nodes ( by their IP address ) and block them indefinitely -- you may have been connected to a tor IP that was blocked by the server -- try to renew your tor IP ( by either restart the tor daemon or enabling the tor control port and sending a renew signal ).

**Comment by dcromster** [comment]
It works! Thank You!

Maybe this question and answer need add to docs?

**Comment by knoxcard** [comment]
Close issue?

**Comment by talmobi** [comment]
Added small usage example for this to the README

https://github.com/talmobi/tor-request#custom-headers

**Comment by knoxcard** [comment]
@talmobi - Nice work bud!
