### ISSUE TITLE
Multi-threading possible?

### ISSUE THREAD

**Issue by aguyinmontreal** [talmobi/tor-request#14]
Hi again!  I set-up multiple workers on my node app (node's multi-threading) using "cluster"(https://nodejs.org/api/cluster.html).

I'm unsure on how to proceed to create a different Tor instance for each worker (something like this: https://stackoverflow.com/questions/14321214/how-to-run-multiple-tor-processes-at-once-with-different-exit-ips ).

Would you be able to guide me a little bit? Thanks

**Comment by talmobi** [comment]
`tor-request` essentially only connects to the tor daemon at the location you specify. So I assume you would have to run multiple tor daemons at different ports and use multiple instance of `tor-request` ( or specify the address each time before you use it ).

It's possible you could run these wrapped around nodes child_process spawns.

Quite busy with other work related matters at the moment - hope it helps.

**Comment by aguyinmontreal** [comment]
My question is simply: can I start (multiple instances of) `tor.exe --default-torrc PATH_TO_TORRC` from inside node?

And, then how do I detect that Tor is fully loaded, running and ready to receive requests?

Thanks!

**Comment by aguyinmontreal** [comment]
I was able to do it by watching the `stdout`
