### ISSUE TITLE
NPM Warnings

### ISSUE THREAD

**Issue by knoxcard** [talmobi/tor-request#18]
warning tor-request > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

warning tor-request > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

warning tor-request > request > node-uuid@1.4.8: Use uuid module instead

**Comment by talmobi** [comment]
updated `request` package versions for v1 and v2 to latest `2.85.x` ( from  `2.67.x` ) -- this may solve some of the warnings.
