### ISSUE TITLE
pass options to request

### ISSUE THREAD

**Issue by thomasspiesser** [talmobi/tor-request#2]
hey,
when I want to set e.g. a User-Agent on a request, I pass on object that contains the url and headers and so on to the request like so

```
options = {
  url: 'test.com',
  headers: {
    'User-Agent': 'something'
  }
}
```

```
request( options, function(error, response, body){})
```

I tried to do the same with your package but that throws `TypeError: Cannot read property 'indexOf' of undefined` at line 34 I think.

I tried passing in the object after the url, which did not throw but I think the options got ignored.

```
tr.request( url, options, function(error, response, body){})
```

Do you have any thoughts on that?
Cheers, and thanks in advance.

**Comment by talmobi** [comment]
Hello!

It seems request checks both opts.uri and opts.url while I only check for opts.uri. You can get around this error if you use uri instead of url. I'll add (params.ui || params.url) in a commit so you can use both.

Does this fix your issue?

**Comment by thomasspiesser** [comment]
Thanks for getting back so quickly. I haven't tried it yet but from what i can see this would fix it. I will close this then. Cheers!
