### ISSUE TITLE
got some error

### ISSUE THREAD

**Issue by justazul** [talmobi/tor-request#20]
Nevermind, just missed the the readme :c

**Comment by talmobi** [comment]
Halåj!

This is probably because you don't have `tor` running.

You can see the README for installing help, it should be pretty easy - some
like `brew install tor && tor` on OSX or `apt-get install tor` on unix.

BR
Christian

**Comment by talmobi** [comment]
I added some better error messages to the newest versions, since this was quite a common issue.
