### ISSUE TITLE
Demo http://tor.jin.fi/ not working 

### ISSUE THREAD

**Issue by davidrocket** [talmobi/tor-request#25]
Hello Talmobi,

First of all, thank for your work of creating this library!

I have tried with many tests, without having success to have a new IP while sending request through Tor. 

The "MY TOR IP" is not working (I did refresh to get the new one), as it shows always the same error, when the test starts:

`{ Error: connect ECONNREFUSED 93.115.95.204:9050
 - Are you running `tor`?
See easy guide here (OSX, Linux, Windows):
https://github.com/talmobi/tor-request#requirements

 Quickfixes:
  OSX: `brew install tor && tor`         # installs and runs tor
  Debian/Ubuntu: `apt-get install tor`   # should auto run as daemon after install

    at SocksClient._closeSocket (*/node_modules/socks/build/client/socksclient.js:355:32)
    at SocksClient.onError (*/node_modules/socks/build/client/socksclient.js:328:14)
    at Socket._onError (*/node_modules/socks/build/client/socksclient.js:202:39)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  options: 
   { proxy: { ipaddress: '93.115.95.204', port: 9050, type: 5 },
     destination: { port: 80, host: 'api.ipify.org' },
     command: 'connect' } }
`

I did try to install Tor on my linux kit, then update the test with this Tor Address (linux-machine-address, 9050), but the same error was shown!

Another test, which has worked for me, is to install the Tor-Browser, then use the Address of Tor-Browser preconfiged proxy, and its port 9150... This one has worked. The above 2 are not.

So any hint, on how I should change the test, would be appreciated! The test is grasped from your README file.
Thank you,
David

**Comment by talmobi** [comment]
Halåj,

My suspicion is that tor isn't running, you may have been able to install it on your linux box but it may not have started running automatically as a daemon process.

try these commands in the terminal/command line:

`which tor`

this tells you where tor is installed ( and confirms that it is indeed installed ).

then try to run it manually by simply typing in

`tor`

Two things can happen here

1. tor starts running and now the tests should work
2. the tor fails to run because tor is already running -> then have to debug some more.

**Comment by talmobi** [comment]
@davidrocket Did you get it working?

**Comment by davidrocket** [comment]
@talmobi I've ended up with my own solution:

1. Set up a tor proxy server
2. Each request to the internet called with request library is wrapped up with an proxy config (to my tor server)

It works well, except I have to change the tor chain (network) every 2 minutes to keep the anonymousity! 

Anyway thank for your lib!

**Comment by talmobi** [comment]
Yes it is very important that you install and run your own tor client which does all the heavy lifting for you dealing with the tor network, see: https://github.com/talmobi/tor-request#requirements

Glad you got it working~

**Comment by optionsx** [comment]
> Yes it is very important that you install and run your own tor client which does all the heavy lifting for you dealing with the tor network, see: https://github.com/talmobi/tor-request#requirements
> 
> Glad you got it working~

i'd like to use the demo server, is there any way?

**Comment by talmobi** [comment]
@optionsx I'm not sure what you mean -- there's a demo here: http://tor.jin.fi

but in order to use the tor network, you need to use a tor client (that his library helps you connect to through node.js) -- it is easy to install a tor client, see: https://github.com/talmobi/tor-request#requirements

**Comment by optionsx** [comment]
Ah, i was hoping i could use a reverse proxy, since 1 its more work to get
started 2 not sure if its doable with replit

**Comment by talmobi** [comment]
@optionsx it doesn't really make sense for connecting to the tor network -- especially a public one. If you have a computer then you can run the tor client and connect.
