### ISSUE TITLE
Error: Received invalid Socks5 initial handshake (invalid socks version)

### ISSUE THREAD

**Issue by leonardorifeli** [talmobi/tor-request#38]
I'm running this:

```js
let url = 'http://leonardorifeli.tech/';
var tr = require('tor-request');

tr.setTorAddress('127.0.0.1', '9051');
tr.TorControlPort.password = 'giraffe'

tr.request(url, function (err, res, body) {
	console.log('hahahahahha', err, res, body);
});
```

Receiving this error: 

```
hahahahahha { Error: Received invalid Socks5 initial handshake (invalid socks version)
```

My torrc file:

```
# sample torrc file
ControlPort 9051
HashedControlPassword 16:14136122DD25F6D8605B28CC41863F6E82202494594F613D3441F9534D
SocksPort 127.0.0.1:auto
```

**Comment by talmobi** [comment]
Halåj~

the default IP address and port is `127.0.0.1` and `9050` -- you probably want to set the port to `9050` instead of `9051`.

`9051` is used by the TorControl service ( an TCP API endpoint you can use to communicate with your tor client )

**Comment by leonardorifeli** [comment]
@talmobi I fixed with this article: http://blog.kashishgupta.in/2016/10/31/anonymous-tor-request-using-nodejs/#codesyntax_14
