### ISSUE TITLE
Control Port authentication issue?

### ISSUE THREAD

**Issue by dapphp** [talmobi/tor-request#4]
I haven't tested it personally, but this is based on a post on StackOverflow at http://stackoverflow.com/questions/38486347/generating-tor-controlport-password

It looks like they're getting errors about failing to authenticate due to missing quotes.  In the [source](https://github.com/talmobi/tor-request/blob/master/index.js#L134) it looks like the password is not wrapped in quotes which it should be.

Probably should change:

    var commands = [
      'authenticate '+ password +'', // authenticate the connection

to:

    var commands = [
      'authenticate "'+ password +'"', // authenticate the connection

if the password is not empty.

**Comment by talmobi** [comment]
Hello!

You were right, the password when not an empty string requires quotes around it. I tested with both empty and non-empty passwords successfully!

I also updated the README to better explain how to generate and configure the password and use the ControlPort.

Thanks for your help!
