### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:9050

### ISSUE THREAD

**Issue by PrasannaBrabourame** [talmobi/tor-request#40]
getting error connect ECONNREFUSED 127.0.0.1:9050

**Comment by talmobi** [comment]
Halåj~

Can you post the full error? Are you sure you're running `tor`?

**Comment by PrasannaBrabourame** [comment]
Thanks for your immediate response. After running the tor.exe. It is working fine now.

**Comment by talmobi** [comment]
Great success~
