### ISSUE TITLE
connect(), disconnect() functions and reusing one connection...

### ISSUE THREAD

**Issue by knoxcard** [talmobi/tor-request#44]
@talmobi - question for you, would something like this be possible with tor and this module?

tor.js
```
var exports = {}

// connect() - connect to existing Tor socks5 proxy
exports.connect = cb => {
	var tor = require('tor-request')
	tor.TorControlPort.password = process.env.tor_password
	return cb(tor)
}
exports.request = () => {
   // just reuse the request object, kind of like a tor request connection pool?
}
exports.renew = () => {
   // renew the tor session
}
exports.ip = () => {
   // get the outgoing ip address
}
exports.close = () => {
   // disconnect from Tor socks5 proxy
}
module.exports = exports
```

**Comment by talmobi** [comment]
Halåj~

I have seen this but don't have time to think about it right now, will try and remember to revisit this soon. Thanks~

**Comment by talmobi** [comment]
Something like that should probably be possible, the `tor-request` module is mutable/global (as are most/all node required modules)

**Comment by knoxcard** [comment]
Hmm, we can either keep this ticket open or close it and transfer this over to Projects perhaps?

**Comment by talmobi** [comment]
You mean the password for the Tor ControlPort access?

All the heavy lifting like connection handling etc is done by the `tor` binary/service itself. This module so far is only a thin wrapper for connecting to that service with an easy to use API along with a small JavaScript friendly API to connect to the optional ControlPort service (which is a slightly complex TCP API provided by the main tor service)

I don't immediately see why connection pooling should be considered at the level of abstraction that this module occupies. If it is needed it might be best to do it as a separate project -- either as another layer ontop/below this module or simply a fresh project as such using perhaps `socks-proxy-agent` more directly.

Haven't put much thought into this yet though so I may be wrong, but these are my current first impressions.

**Comment by knoxcard** [comment]
Okay sounds good, thanks for the quick reply!

**Comment by talmobi** [comment]
Closing this as it's out of scope for this module and IMHO better to let be handled by the underlying tor process itself.
