### ISSUE TITLE
[Feature] implement requestSync/torRequestSync

### ISSUE THREAD

**Issue by katalonne** [talmobi/tor-request#46]
@talmobi
It would be a nice feature. I would implement it

**Comment by skmohammadi** [comment]
hi. i need this feature.

**Comment by talmobi** [comment]
You have to remember that this would only be a hack to your node code. The tor binary itself will do whatever it wants.

Also I'm 99% sure you should be fine without this kind of feature in this module itself as you control how you want to execute your own node code. In other words, this isn't something that is desperately needed for this module to do its job.

Hope this helps~

**Comment by talmobi** [comment]
Closing this as it's out of scope for this module.
