### ISSUE TITLE
publically available Tor client

### ISSUE THREAD

**Issue by jjg77** [talmobi/tor-request#50]
"Either run it yourself locally (recommended) or specify the address for a publically available one."

How can I use a publically available Tor client?

**Comment by talmobi** [comment]
There may be some running around but I wouldn't trust them. Just run it yourself it's definitely the way to go. In fact I should probably remove that line form the README since it's really not a good idea.

**Comment by talmobi** [comment]
Rephrased the README regarding this: https://github.com/talmobi/tor-request/commit/c5a45eab89c9637b4ffb7e48232539fe7af75c5d
