### ISSUE TITLE
[question] Publically available Tor clients?

### ISSUE THREAD

**Issue by ekkis** [talmobi/tor-request#55]
In the README, under the Requirements section, it is stated that one needs a client:

> A Tor client. Either run it yourself locally (recommended) or specify the address for a publically available one.

I have searched for "public tor clients" but come up empty.  do these things have a better name? can anyone point me to an authoritative source of where I might find one? I want to use this library without running a local daemon.  I can't as I'm developing on the Now cloud service

**Comment by talmobi** [comment]
Hello,

I think I removed that part from the README at some point recently. It's really not a good idea. It was mainly to demonstrate that you could set the address (e.g. if creating a LAN cluster using the same client).

Installing the client on your own machine is 99.9% the best way to go as third-party clients are not trustworthy (only for demo purposes).
