### ISSUE TITLE
security check

### ISSUE THREAD

**Issue by Agnostion** [talmobi/tor-request#61]
Does not give access to data of Cloudflare sites, throwing 403 error. I tried to set the user-agent.
What else can i try?

**Comment by talmobi** [comment]
Hello there,

Can you describe the issue in more detail?

What are you trying to do?

A code sample?

Where does the error show up?

**Comment by Agnostion** [comment]
Of course, here's a simple request:
```JavaScript
const tr = require('tor-request');
tr.TorControlPort.password = 'giraffe';
tr.setTorAddress('localhost', 9050);

tr.request({
        url: '*DEL*', headers: { 'user-agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36' }
    }, function (err, res, body) {
        console.log(res.statusCode);
    });
```

**Comment by talmobi** [comment]
Looks like they're blocking a good chunk of tor exit nodes and required a CAPTCHA on them.

If it's temporary you could manually do the captcha and use whatever auth cookie they give to gain temporary access until the cookie expires/is invalidated.

**Comment by Agnostion** [comment]
Thanks for the explanation.
But I don't quite understand how to do this, can you tell me?
Or you can already close the issue.)

**Comment by Agnostion** [comment]
And yes, when I just use the Tor Browser, there is no security check. Only if I use the tor-request.

**Comment by talmobi** [comment]
When you use the browsers you should be able to see the request that the browser sends. You should be able to see all the headers it's sending, including user-agent etc.

If you copy all those headers and use the same tor exit node, it should work.

You can see the headers/network request details by opening the dev console available in most browsers.

**Comment by Agnostion** [comment]
Got it. Thank you for help.)
