### ISSUE TITLE
err: SocksClientError: Proxy connection timed out

### ISSUE THREAD

**Issue by Trard** [talmobi/tor-request#69]
I get an error  when I use the docker

![image](https://raw.githubusercontent.com/Trard/dockertor/master/docs/images/docker.png)

see https://github.com/Trard/dockertor

**Comment by Trard** [comment]
Maybe I found what caused this error
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/tor --RunAsDaemon 1": stat /usr/bin/tor --RunAsDaemon 1: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled
```

**Comment by Trard** [comment]
> 
> 
> Maybe I found what caused this error
> 
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/tor --RunAsDaemon 1": stat /usr/bin/tor --RunAsDaemon 1: no such file or directory: unknown. ERRO[0000] error waiting for container: context canceled

It has been fixed by **https://github.com/Trard/dockertor/commit/c793534906f2ff019a0dd058fa207660a5befa3a**
(see: https://stackoverflow.com/questions/60875207/docker-oci-runtime-create-failed-container-linux-go349-starting-container-pro)

But here is a new error:
```
err: SocksClientError: Proxy connection timed out
      at SocksClient._closeSocket (/test/node_modules/socks/build/client/socksclient.js:368:32)
      at SocksClient.onEstablishedTimeout (/test/node_modules/socks/build/client/socksclient.js:257:18)
      at Timeout._onTimeout (/test/node_modules/socks/build/client/socksclient.js:206:45)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7) {
    options: { proxy: [Object], destination: [Object], command: 'connect' }
  }
```

**Comment by Trard** [comment]
> 
> 
> > Maybe I found what caused this error
> > docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/tor --RunAsDaemon 1": stat /usr/bin/tor --RunAsDaemon 1: no such file or directory: unknown. ERRO[0000] error waiting for container: context canceled
> 
> It has been fixed by **[Trard/dockertor@c793534](https://github.com/Trard/dockertor/commit/c793534906f2ff019a0dd058fa207660a5befa3a)** (see: https://stackoverflow.com/questions/60875207/docker-oci-runtime-create-failed-container-linux-go349-starting-container-pro)
> 
> But here is a new error:
> 
> ```
> err: SocksClientError: Proxy connection timed out
>       at SocksClient._closeSocket (/test/node_modules/socks/build/client/socksclient.js:368:32)
>       at SocksClient.onEstablishedTimeout (/test/node_modules/socks/build/client/socksclient.js:257:18)
>       at Timeout._onTimeout (/test/node_modules/socks/build/client/socksclient.js:206:45)
>       at listOnTimeout (node:internal/timers:557:17)
>       at processTimers (node:internal/timers:500:7) {
>     options: { proxy: [Object], destination: [Object], command: 'connect' }
>   }
> ```

This error was only on docker run [image id]. I used docker run -p 9050:9050 [image id] and all worked.

**Comment by Trard** [comment]
nice

**Comment by talmobi** [comment]
@Trard thank you very much for this writeup~
