### ISSUE TITLE
Which SOCKS version does it use?

### ISSUE THREAD

**Issue by BossMode** [talmobi/tor-request#8]
Just a quick question I didn't look through source code, do you prevent potential DNS leaks by using SOCKS4a? Or?

**Comment by talmobi** [comment]
Hello!

I'm using the https://github.com/JoshGlazebrook/socks library which supports, 4, 4a, and 5.

By default I'm using 5: https://github.com/talmobi/tor-request/blob/master/index.js#L21

**Comment by BossMode** [comment]
Thanks for quick response ;)
